Missing echo if no desktop exists
whizzzkid/bing-wallpapers-for-linux pull request #13
Opened 2017-10-26 11:01 UTC by aggsol

See title and change.

2017-10-26 21:48 UTC, whizzzkid requested changes
Other files in there exist for a purpose. launchpad automatically pulls the repo and builds this into a debian package which is then pushed over apt as an update. If you remove that then everything fails.

Please checkout all the existing files one by one back into this commit except `bingwallpaper` Then make the changes requested in that file only.

Rest this looks better. Looking forward to review this.

2017-10-26 21:48 UTC, whizzzkid commented on README.md
>  # Bing Wallpapers For Linux
Any changes to Readme will not be accepted.

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> -#!/bin/bash
why do we need to change this?

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +reqImg="$bing$api$format$day$market$const"
not needed

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +#echo "request: $reqImg"
remove this comment

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +while  true
not needed

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +  apiResp=$(curl -s "$reqImg")
ditto

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> -  # Default image URL in case the required is not available.
why was the comment removed?

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +  mkdir -p "$path"
not needed

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +  curl -s -o "$path$imgName" "$reqImgURL"
ditto

2017-10-26 21:48 UTC, whizzzkid commented on bingwallpaper
> +  : "${XDG_CURRENT_DESKTOP:=}"
this is confusing.

2017-10-26 21:48 UTC, whizzzkid commented on debian/changelog
> -bingwallpaper (0.5-1) UNRELEASED; urgency=medium
please do not remove existing files.

2017-10-26 21:48 UTC, whizzzkid commented on debian/control
> -Source: bingwallpaper
do not remove existing files

2017-10-26 21:48 UTC, whizzzkid commented on debian/copyright
> -Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
do not remove existing files

2017-10-26 21:48 UTC, whizzzkid commented on debian/install
> -bingwallpaper usr/bin
do not remove existing files

2017-10-26 21:48 UTC, whizzzkid commented on debian/postinst
> -#!/bin/sh
do not remove existing files

2017-10-26 21:48 UTC, whizzzkid commented on debian/rules
> -#!/usr/bin/make -f
do not remove existing files

2017-10-26 21:48 UTC, whizzzkid commented on debian/source/format
> -1.0
do not remove existing files

2017-10-27 07:01 UTC, aggsol commented
Aaargh sorry, I just wanted the first commit as PR. The rest are my own changes. :-(

2017-10-27 07:01 UTC, closed without merging